# Generated by Django 5.2.3 on 2025-07-03 01:20

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log de auditoría', 'verbose_name_plural': 'Logs de auditoría'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['code'], 'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['business_name'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='sri_certificate',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sri_environment',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sri_password',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='module',
            field=models.CharField(blank=True, choices=[('core', 'Core'), ('users', 'Usuarios'), ('pos', 'Punto de Venta'), ('inventory', 'Inventario'), ('invoicing', 'Facturación'), ('purchases', 'Compras'), ('accounting', 'Contabilidad'), ('reports', 'Reportes'), ('settings', 'Configuraciones')], max_length=50, verbose_name='Módulo'),
        ),
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.CharField(blank=True, max_length=200, verbose_name='Encargado'),
        ),
        migrations.AddField(
            model_name='company',
            name='actividad_economica',
            field=models.CharField(blank=True, max_length=200, verbose_name='Actividad económica'),
        ),
        migrations.AddField(
            model_name='company',
            name='cedula_representante',
            field=models.CharField(blank=True, max_length=10, verbose_name='Cédula del representante'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='Ecuador', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Empresa por defecto'),
        ),
        migrations.AddField(
            model_name='company',
            name='obligado_contabilidad',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2, verbose_name='Obligado a llevar contabilidad'),
        ),
        migrations.AddField(
            model_name='company',
            name='representante_legal',
            field=models.CharField(blank=True, max_length=200, verbose_name='Representante legal'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('VIEW', 'Ver'), ('LOGIN', 'Iniciar sesión'), ('LOGOUT', 'Cerrar sesión'), ('EXPORT', 'Exportar'), ('IMPORT', 'Importar'), ('SEND_SRI', 'Enviar al SRI'), ('EMAIL_SENT', 'Email enviado')], max_length=20, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Cambios realizados'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='sri_establishment_code',
            field=models.CharField(default='001', max_length=3, validators=[django.core.validators.RegexValidator(message='Debe ser 3 dígitos', regex='^\\d{3}$')], verbose_name='Código establecimiento SRI'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='company_logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='schema_name',
            field=models.CharField(blank=True, max_length=63, unique=True, verbose_name='Esquema de base de datos'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='core_audit__action_82b39f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['module'], name='core_audit__module_eecc11_idx'),
        ),
    ]
