# Generated by Django 5.2.3 on 2025-06-26 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document_number',
            field=models.CharField(blank=True, help_text='Número de cédula o documento de identidad (opcional para registro social)', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El número de documento solo puede contener números y guiones.', regex='^[\\d\\-]+$')], verbose_name='Número de documento'),
        ),
    ]
