# Generated by Django 5.2.3 on 2025-06-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='document_number',
            field=models.CharField(blank=True, help_text='Cédula, RUC o pasaporte', max_length=20, verbose_name='Número de documento'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Número de intentos de login fallidos', verbose_name='Intentos fallidos'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text='Usuario debe cambiar contraseña en siguiente login', verbose_name='Forzar cambio de contraseña'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último cambio de contraseña'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última actividad'),
        ),
    ]
