# Generated by Django 5.2.3 on 2025-07-01 02:14

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo_identificacion', models.CharField(choices=[('05', 'Cédula'), ('04', 'RUC'), ('06', 'Pasaporte'), ('07', 'Consumidor Final'), ('08', 'Identificación del Exterior')], max_length=2)),
                ('identificacion', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=300)),
                ('direccion', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'unique_together': {('company', 'identificacion')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('establecimiento', models.CharField(default='001', max_length=3)),
                ('punto_emision', models.CharField(default='001', max_length=3)),
                ('secuencial', models.CharField(max_length=9)),
                ('numero_factura', models.CharField(max_length=17)),
                ('fecha_emision', models.DateTimeField()),
                ('clave_acceso', models.CharField(blank=True, max_length=49, unique=True)),
                ('subtotal_sin_impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_0', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_12', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_ice', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('propina', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('importe_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado_sri', models.CharField(default='PENDIENTE', max_length=20)),
                ('numero_autorizacion', models.CharField(blank=True, max_length=49)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('xml_autorizado', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.customer')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'unique_together': {('company', 'establecimiento', 'punto_emision', 'secuencial')},
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('forma_pago', models.CharField(choices=[('01', 'Sin utilización del sistema financiero'), ('15', 'Compensación de deudas'), ('16', 'Tarjeta de débito'), ('17', 'Dinero electrónico'), ('18', 'Tarjeta prepago'), ('19', 'Tarjeta de crédito'), ('20', 'Otros con utilización del sistema financiero')], max_length=2)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plazo', models.IntegerField(default=0)),
                ('unidad_tiempo', models.CharField(default='dias', max_length=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.invoice')),
            ],
            options={
                'verbose_name': 'Pago de Factura',
                'verbose_name_plural': 'Pagos de Facturas',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo_principal', models.CharField(max_length=25)),
                ('codigo_auxiliar', models.CharField(blank=True, max_length=25)),
                ('descripcion', models.CharField(max_length=300)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tiene_iva', models.BooleanField(default=True)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5)),
                ('tiene_ice', models.BooleanField(default=False)),
                ('porcentaje_ice', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'unique_together': {('company', 'codigo_principal')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo_principal', models.CharField(max_length=25)),
                ('codigo_auxiliar', models.CharField(blank=True, max_length=25)),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_total_sin_impuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('porcentaje_ice', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_ice', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.product')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Facturas',
            },
        ),
        migrations.CreateModel(
            name='SRIConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('certificate_file', models.FileField(help_text='Archivo de certificado P12', upload_to='certificates/')),
                ('certificate_password', models.CharField(help_text='Contraseña del certificado P12', max_length=255)),
                ('environment', models.CharField(choices=[('test', 'Pruebas'), ('production', 'Producción')], default='test', max_length=20)),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_host_user', models.EmailField(max_length=254)),
                ('email_host_password', models.CharField(max_length=255)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sri_config', to='core.company')),
            ],
            options={
                'verbose_name': 'Configuración SRI',
                'verbose_name_plural': 'Configuraciones SRI',
            },
        ),
        migrations.CreateModel(
            name='SRILog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('clave_acceso', models.CharField(max_length=49)),
                ('proceso', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('response_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.invoice')),
            ],
            options={
                'verbose_name': 'Log SRI',
                'verbose_name_plural': 'Logs SRI',
            },
        ),
    ]
